name: Publish Release

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - .github/workflows/*

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'Wox.Plugin.Runner/plugin.json'
          prop_path: 'Version'
      - run: echo ${{steps.version.outputs.prop}}
      - name: Build
        run: |
          dotnet publish 'Wox.Plugin.Runner/Wox.Plugin.Runner.csproj' -r win-x64 -c Release -o "Runner"
          7z a -tzip "Wox.Plugin.Runner.zip" "Runner/*"
          rm -r "Runner"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "Wox.Plugin.Runner.zip"
          tag_name: "v${{steps.version.outputs.prop}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
